config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'sessions' }
  resources :discussions do
    resources :comments
  end
  root 'discussions#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user, inverse_of: :comments
  belongs_to :discussion, inverse_of: :comments
  validates :content, presence: true
  def self.initialize_with content, opt
    comment = Comment.new content
    comment.user = opt[:user]
    comment.discussion = opt[:discussion]
    comment
  end
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :user, inverse_of: :discussions
  has_many :comments, inverse_of: :discussion, dependent: :destroy
  validates :title,
            length: { minimum: 3},
            presence: true
  validates :description,
            length: { minimum: 3},
            presence: true
  accepts_nested_attributes_for :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :discussions, inverse_of: :user, dependent: :destroy
  has_many :comments, inverse_of: :user, dependent: :destroy

  validates :nickname,
            format: { with: /\A[A-Za-z0-9_.]+\z/ },
            length: { maximum: 255 },
            presence: true
  validates :email,
            format: { with: /\A[A-Za-z0-9_.]+@[A-Za-z0-9_.]+\z/},
            presence: true
  validates :password,
            length: {minimum: 8},
            presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def create
    @discussion = Discussion.find params[:discussion_id]
    @comment =  Comment.initialize_with comment_params, user: current_user, discussion: @discussion
    respond_to do |format|
      if @comment.save
        flash.now[:notice] = "New Comment succesfully added"
        format.js { render layout: false }
        format.html { redirect_to discussion_path @discussion }
      else
        flash.now[:error] = "Error adding new Comment. Content shouldn't be empty!"
        format.html { render :show }
      end
    end
  end
  def edit
    @comment = Comment.find params[:id]
    respond_to do |format|
      format.js {render layout: false}
    end
  end
  def update
    @comment = Comment.find params[:id]
    respond_to do |format|
      if @comment.update comment_params
        flash.now[:notice] = "Comment was succesfully edited!"
        format.js {render layout: false}
        #format.html { redirect_to discussion_path @comment.discussion }
      else
        flash.now[:error] = "Error updating comment. Content shouldn't be empty."
        @comment.reload
        format.js {render layout: false}
      end
    end
  end
  def destroy
    @comment = Comment.find params[:id]
    discussion = @comment.discussion
    respond_to do |format|
      if @comment.destroy
        format.js {render layout: false}
        flash.now[:notice] = "Comment was succesfully destroyed"
      else
        flash.now[:error] = "Comment can't be destroyed!"
      end
      format.html { redirect_to discussion_path discussion }
    end
  end
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @discussions = Discussion.includes(:user).all
  end
  def show
    @discussion = Discussion.includes(:user, comments: :user).find params[:id]
    @comment = Comment.new
  end
  def new
    @discussion = Discussion.new
    @discussion.comments.build
  end
  def create
    @discussion = Discussion.new discussion_params
    @discussion.user = current_user
    if @discussion.save
      flash[:notice] = "New Discussion Succesfully Created"
      redirect_to discussion_path @discussion
    else
      flash[:error] = "New Discussion should have Title and Description"
      render :new
    end
  end
  def edit
    @discussion = Discussion.find params[:id]
  end
  def update
    @discussion = Discussion.find params[:id]
    if @discussion.update_attributes discussion_params
      flash[:notice] = 'Discussion Update Successfully'
      redirect_to discussion_path @discussion
    else
      flash[:error] = 'Error updating Discussion, check your attributes please'
      render :edit
    end
  end
  def destroy
    @discussion = Discussion.find params[:id]
    if @discussion.destroy
        flash[:notice] = "Discussion was succesfully destroyed"
        redirect_to discussions_path
      else
        flash[:error] = "Discussion can't be destroyed!"
        render :show
      end
  end


  def discussion_params
    params.require(:discussion).permit(:title,:description)
  end
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_path?
    current_page?(new_user_session_path()) ||
        current_page?(user_session_path()) ||
        current_page?(new_user_password_path()) ||
        current_page?(edit_user_password_path()) ||
        current_page?(cancel_user_registration_path()) ||
        current_page?(new_user_registration_path()) ||
        current_page?(edit_user_registration_path())
  end

  def not_user_path?
    !user_path?
  end

  def current_nickname
    current_user.nickname
  end
end

app/helpers/disscussion_helper.rb
module DisscussionHelper
end

app/views/application/_login.slim
= simple_form_for User.new, url: user_session_url, html: {class: "form-inline"} do |f|
  .form-group>
    = f.label 'Email address:', class: 'sr-only'
    .input-group
      .input-group-addon @
      = f.input_field :email, class: 'form-control', placeholder: 'Enter email'

  .form-group>
    = f.label 'Password:', class: 'sr-only'
    = f.input_field :password, class: 'form-control', placeholder: 'Password'
  .checkbox>
    label
      = f.input_field :remember_me, as: :boolean
      | Remember me
  = f.button :submit, 'Sign in'

app/views/application/_logout.slim
=link_to "Sign Out", destroy_user_session_url, class: "btn btn-default", method: :delete

app/views/comments/_comment.slim
div id="#{'comment'+comment.id.inspect}"
  .panel.panel-default
    .panel-body
      = comment.content
    .panel-footer
      = comment.user.nickname
      |   |
      = comment.created_at.strftime "%H:%M:%S %a %Y"
      .pull-right
        => link_to 'Edit', edit_discussion_comment_path(comment.discussion, comment), remote: true, class: "edit-link"
        = link_to 'Delete', discussion_comment_path(comment.discussion, comment), method: :delete,remote: true, data: {confirm: 'Are you sure?'}

app/views/comments/_form.slim
.panel.panel-default
  = simple_form_for comment, remote: true, url: discussion_comment_url(comment.discussion.id, comment.id ) do |f|
    .panel-body
      = f.input :content
    .panel-footer
      = f.button :submit

app/views/comments/_new_form.slim
= simple_form_for Comment.new, remote: true, url: discussion_comments_path( discussion_id: id ) do |f|
  = f.input :content, label: 'Add new Comment'
  = f.button :submit, 'Add Comment'

app/views/comments/create.js.erb
var commentID = '<%= j "comment"+@comment.id.inspect %>';
$('#comments').append("<%= j render partial: 'comment', locals: {comment: @comment} %>");
$('#new_comment textarea').val('');

app/views/comments/destroy.js.erb
var selector = '<%= j "#comment"+@comment.id.inspect %>';var selector = '<%= j "#comment"+@comment.id.inspect %>';
$(selector).html('');

app/views/comments/edit.js.erb
var selector = '<%= j "#comment"+@comment.id.inspect %>';
$(selector).html("<%= escape_javascript render partial: 'form', locals: {comment: @comment} %>");

app/views/comments/update.js.erb
var selector = '<%= j "#comment"+@comment.id.inspect %>';
$(selector).html("<%= j render partial: 'comment', locals: {comment: @comment} %>");
$('#flash-area').html("<%= j  bootstrap_flash %>");

app/views/discussions/_discussion.slim
= simple_form_for discussion do |f|
  = f.input :title, label: "Enter title of new disscussion:"
  = f.input :description,  label: "Enter description, please:"
  = f.button :submit, class: "btn btn-primary"

app/views/discussions/_discussion_row.slim
tr
  td = link_to discussion_row.title, discussion_path(discussion_row)
  td = discussion_row.user.nickname

app/views/discussions/edit.slim
= render @discussion

app/views/discussions/index.slim
- content_for :title do
  | All discussions |
  = APP_NAME

.panel
  .panel-heading.clearfix
    .col-lg-9
      h1 All discussions
    .pull-right#new-discussion
      = link_to 'Add New Discussion', new_discussion_path, {class: 'btn btn-primary'}
    span.clearfix

  table.table
    tr
      th Title
      th Created By
    =render partial: "discussion_row", collection: @discussions

app/views/discussions/new.slim
= render @discussion

app/views/discussions/show.slim
- content_for :title do
  = @discussion.title

.panel.panel-default
  .panel-heading
    h1= @discussion.title
  .panel-body
    p= @discussion.description
  .panel-footer.clearfix
    => @discussion.user.nickname
    |   |
    =< @discussion.updated_at.strftime "%H:%M:%S %a %Y"
    .pull-right
      => link_to 'Edit', edit_discussion_path(@discussion)

      => link_to 'Delete', discussion_path(@discussion), method: :delete, data: {confirm: 'Are you sure?'}

#comments
  = render @discussion.comments

= render partial: 'comments/new_form', locals: {id: @discussion.id}

app/views/layouts/application.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : APP_NAME
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
      /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="#{{root_path}}"= APP_NAME
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav.navbar-left
            li= link_to "Link 1", "/path1"
            li= link_to "Link 2", "/path2"
            li= link_to "Link 3", "/path3"
          .nav.navbar-form.navbar-right
             - if not_user_path?
              - if user_signed_in?
                |
                 Hello,
                =<> current_nickname
                =render partial: "logout"
              - else
                =render partial: "login"


    .container
      .row
        .col-lg-9
          #flash-area
            = bootstrap_flash
          = yield
    footer
      .container
        p
        | &copy; Company
        = Date.today.year